load data_country
load clusters

features = {
    "Child_mortality",...
    "Exports",...
    "Health",...
    "Imports",...
    "Income",...
    "Inflation",...
    "Life_expectancy",...
    "Total_fertility",...
    "GDPP"
};

% Find the unique cluster labels
unique_clusters = unique(bel'); % Should give [1, 2, 3] if you have 3 clusters

% Initialize an array to store the means
cluster_means = zeros(length(unique_clusters), size(Countrydata, 2));

% Loop through each cluster and calculate means for all features
for i = 1:length(unique_clusters)
    cluster_idx = (bel' == unique_clusters(i)); % Logical index for current cluster
    cluster_data = Countrydata(cluster_idx, :); % Extract rows for this cluster
    cluster_means(i, :) = mean(cluster_data, 1); % Calculate mean of each feature
    cluster_stdvs(i, :) = std(cluster_data, 1); % Calculate standard deviation of each feature 
end

% Display the means
disp('Mean of each feature for each cluster:');
disp(array2table(cluster_means, 'VariableNames', {'Child_mortality','Exports','Health', ...
    'Imports','Income','Inflation','Life_expectancy','Total_fertility','GDPP'}, ...
    'RowNames', {'Cluster1', 'Cluster2', 'Cluster3'}));
disp('Standard Deviation of each feature for each cluster:')
disp(array2table(cluster_stdvs, 'VariableNames', {'Child_mortality','Exports','Health', ...
    'Imports','Income','Inflation','Life_expectancy','Total_fertility','GDPP'}, ...
    'RowNames', {'Cluster1', 'Cluster2', 'Cluster3'}));
